### ISSUE TITLE
Major issue, [ BUG INDUCING ] 

### ISSUE THREAD

**Issue by rxx-git** [m1ten/oxymake#8]
### MASSIVE ISSUE.
This is issue will cause bugs within the code it's easily avoidable and I'm not sure why you just didn't fix it when you spotted it.
The bug being a major critical issue with the programming language, rust is a doo doo shit fart asmr language just use C - rxx

**Comment by Abb1x** [comment]
ANSI C*

**Comment by m1ten** [comment]
"It's not a bug, it's a feature."

**Comment by rxx-git** [comment]
**No it's not it is actually a bug**

**Comment by rxx-git** [comment]
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
Open this
